EMBEDDING_MODEL = "all-MiniLM-L6-v2"
EMBEDDING_DIMENSION = 384
VECTOR_INDEX_NAME = "chunk_embedding_index"

MAX_CONVERSATION_ID_LENGTH = 200
MAX_DOCUMENT_TITLE_LENGTH = 300
MAX_DOCUMENT_CHARACTERS = 50_000
MAX_QUESTION_LENGTH = 5_000
MAX_TOP_K = 5
